apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: iib-{{ item.value['iib'] }}
  namespace: {{ internal_registry_ns }}
spec:
  image: {{ iib_dest_registry}}/{{ iib_dest_image }}:{{ item.value['iib'] }}
  sourceType: grpc
  displayName: IIB {{ item.value['iib'] }}
